"""Additional German e-invoice prompt guides — batch 3."""


def rechnungsberichtigung_vs_storno() -> str:
    """381 vs 384: Wann Gutschrift, wann Korrekturrechnung?"""
    return (
        "# Rechnungsberichtigung vs. Stornorechnung\n\n"
        "## Ueberblick\n"
        "Die Unterscheidung zwischen Gutschrift (381), Korrekturrechnung (384) "
        "und Stornierung ist einer der haeufigsten Fehlerquellen in der "
        "deutschen E-Rechnung.\n\n"
        "## TypeCode-Entscheidungsbaum\n\n"
        "### TypeCode 381 — Gutschrift (Credit Note)\n"
        "**Verwendung:** Teilweise oder vollstaendige Rueckerstattung\n"
        "- Ware teilweise zurueckgegeben\n"
        "- Nachtraeglicher Preisnachlass / Bonus\n"
        "- Schadensersatzleistung\n"
        "- Rueckabwicklung einzelner Positionen\n\n"
        "**Pflichtfelder:**\n"
        "- `preceding_invoice_number` (BT-25) — Bezug zur Originalrechnung\n"
        "- `preceding_invoice_date` (BT-26) — Datum der Originalrechnung\n"
        "- Betraege sind **positiv** (nicht negativ!)\n\n"
        "### TypeCode 384 — Korrekturrechnung (Corrected Invoice)\n"
        "**Verwendung:** Inhaltlicher Fehler in der Originalrechnung\n"
        "- Falscher Steuersatz angewendet\n"
        "- Falsche Menge / Preis\n"
        "- Falscher Empfaenger\n"
        "- Fehlende Pflichtangaben\n\n"
        "**Pflichtfelder:**\n"
        "- `preceding_invoice_number` (BT-25)\n"
        "- `preceding_invoice_date` (BT-26)\n"
        "- Betraege zeigen die **Differenz** (Korrektur)\n\n"
        "### Stornierung (zwei Dokumente)\n"
        "**Verwendung:** Komplette Aufhebung der Originalrechnung\n"
        "1. Stornorechnung (381) ueber den **vollen Betrag**\n"
        "2. Neue korrekte Rechnung (380) mit neuer Rechnungsnummer\n\n"
        "## Entscheidungshilfe\n\n"
        "| Situation | Loesung | TypeCode |\n"
        "|-----------|---------|----------|\n"
        "| Kunde gibt 3 von 10 Stueck zurueck | Gutschrift | 381 |\n"
        "| Nachtraeglicher 5% Rabatt | Gutschrift | 381 |\n"
        "| Falscher MwSt-Satz (19% statt 7%) | Korrektur | 384 |\n"
        "| Falsche Rechnungsadresse | Storno + Neuausstellung | 381 + 380 |\n"
        "| Leistung wurde nie erbracht | Storno | 381 (voller Betrag) |\n"
        "| Zahlendreher im Preis | Korrektur | 384 |\n"
        "| Fehlender Leistungszeitraum | Korrektur | 384 |\n\n"
        "## Steuerliche Auswirkungen\n"
        "- **381:** Reduziert die USt-Schuld des Leistenden, Empfaenger "
        "muss Vorsteuer berichtigen (§17 UStG)\n"
        "- **384:** Ersetzt die fehlerhafte Rechnung rueckwirkend, "
        "Vorsteuerabzug richtet sich nach korrekter Rechnung\n"
        "- Bei §14c UStG (unberechtigter Steuerausweis): Immer "
        "Korrektur per 384 + Berichtigung beim Finanzamt\n\n"
        "## Haeufige Fehler\n"
        "- Negative Betraege in 381 (Betraege muessen positiv sein)\n"
        "- Fehlender Bezug zur Originalrechnung (BT-25)\n"
        "- 384 ohne BT-25/BT-26 → wird abgelehnt\n"
        "- Verwechslung: 'Gutschrift' im kaufmaennischen Sinne ≠ "
        "Gutschriftverfahren (TypeCode 389)"
    )


def reverse_charge_steuervertreter_combined() -> str:
    """Reverse Charge + Steuervertreter: Kombiniertes Szenario."""
    return (
        "# Reverse Charge + Steuervertreter (Kombiniert)\n\n"
        "## Wann tritt dieses Szenario auf?\n"
        "Ein auslaendisches Unternehmen (z.B. AT, PL, CZ) erbringt "
        "Bauleistungen in Deutschland und hat einen deutschen "
        "Steuervertreter (Fiskalvertreter) bestellt.\n\n"
        "## Rechtliche Grundlage\n"
        "- **Reverse Charge:** §13b Abs. 2 Nr. 1 / Nr. 4 UStG\n"
        "- **Steuervertreter:** §22a-22e UStG, Art. 204 MwStSystRL\n"
        "- Der Steuervertreter meldet die USt fuer den auslaendischen "
        "Unternehmer in DE an.\n\n"
        "## Feldkonfiguration in der E-Rechnung\n\n"
        "### Seller (= auslaendisches Unternehmen)\n"
        "- `seller_name`: Firmenname des Leistungserbringers\n"
        "- `seller_tax_id`: Auslaendische Steuernummer\n"
        "- `seller_vat_id`: Auslaendische USt-IdNr. (BT-31)\n"
        "- `seller_country_code`: z.B. 'AT', 'PL'\n\n"
        "### Seller Tax Representative (BG-11)\n"
        "- `seller_tax_rep_name` (BT-62): Name des DE-Vertreters\n"
        "- `seller_tax_rep_vat_id` (BT-63): DE-USt-IdNr. des Vertreters\n"
        "- `seller_tax_rep_street` (BT-64): Adresse in DE\n"
        "- `seller_tax_rep_city` (BT-65): Stadt in DE\n"
        "- `seller_tax_rep_postal_code`: PLZ\n"
        "- `seller_tax_rep_country_code`: 'DE'\n\n"
        "### Tax Settings\n"
        "- `tax_category`: 'AE' (Reverse Charge)\n"
        "- `tax_rate`: '0.00'\n"
        "- `tax_exemption_reason`: 'Steuerschuldnerschaft des "
        "Leistungsempfaengers gemaess §13b UStG'\n"
        "- `tax_exemption_reason_code`: 'VATEX-EU-AE'\n\n"
        "## Unterschied: Wann Steuervertreter?\n"
        "| Situation | Steuervertreter noetig? | Reverse Charge? |\n"
        "|-----------|------------------------|------------------|\n"
        "| AT-Firma → DE-Firma (B2B Bauleistung) | Optional | Ja (§13b) |\n"
        "| AT-Firma → DE-Privatperson (B2C) | **Ja, Pflicht** | Nein |\n"
        "| AT-Firma hat DE-Betriebsstaette | Nein | Nein (DE-USt) |\n"
        "| DE-Firma → DE-Firma | Nein | Nein |\n\n"
        "## BR-DE Pruefungen\n"
        "- **BR-DE-3:** Seller nicht in DE → Steuervertreter pruefen\n"
        "- **BR-DE-4 (REP-BT-63):** Steuervertreter muss USt-IdNr. haben\n"
        "- **BT-31:** Seller USt-IdNr. immer Pflicht bei RC\n\n"
        "## Haeufige Fehler\n"
        "- Steuervertreter angegeben, aber Tax Category 'S' statt 'AE'\n"
        "- Tax Rate nicht 0.00 bei Reverse Charge\n"
        "- Fehlende VATEX-EU-AE bei Befreiungsgrund\n"
        "- Seller mit DE-Laendercode, aber Steuervertreter eingetragen\n"
        "- BT-63 fehlt beim Steuervertreter"
    )


def teilrechnung_workflow() -> str:
    """Teilrechnung → Schlussrechnung: Vollstaendiger Workflow."""
    return (
        "# Teilrechnung → Schlussrechnung Workflow\n\n"
        "## Ueberblick\n"
        "Bei Projekten (Bau, IT, Beratung) werden haeufig "
        "Teilrechnungen gestellt, bevor die Schlussrechnung "
        "den Vorgang abschliesst.\n\n"
        "## Lebenszyklus\n\n"
        "### 1. Vertrag / Auftrag\n"
        "- Projektreferenz (BT-11) oder Vertragsnummer (BT-12) festlegen\n"
        "- Diese Referenz muss in **allen** Teilrechnungen identisch sein!\n\n"
        "### 2. Abschlagsrechnung 1 (TypeCode 875)\n"
        "```json\n"
        "{\n"
        '  "type_code": "875",\n'
        '  "invoice_id": "AR-2025-001",\n'
        '  "project_reference": "PROJ-2025-42",\n'
        '  "invoice_note": "1. Abschlagsrechnung — 30% nach Planungsphase",\n'
        '  "items": [{"description": "Planungsleistung (30%)", '
        '"quantity": "1", "unit_price": "15000.00", "tax_rate": "19.00"}]\n'
        "}\n"
        "```\n\n"
        "### 3. Abschlagsrechnung 2 (TypeCode 875)\n"
        "```json\n"
        "{\n"
        '  "type_code": "875",\n'
        '  "invoice_id": "AR-2025-002",\n'
        '  "project_reference": "PROJ-2025-42",\n'
        '  "invoice_note": "2. Abschlagsrechnung — 40% nach Rohbauphase",\n'
        '  "items": [{"description": "Rohbauleistung (40%)", '
        '"quantity": "1", "unit_price": "20000.00", "tax_rate": "19.00"}]\n'
        "}\n"
        "```\n\n"
        "### 4. Schlussrechnung (TypeCode 877)\n"
        "```json\n"
        "{\n"
        '  "type_code": "877",\n'
        '  "invoice_id": "SR-2025-001",\n'
        '  "project_reference": "PROJ-2025-42",\n'
        '  "prepaid_amount": "35000.00",\n'
        '  "invoice_note": "Schlussrechnung — Gesamtabrechnung abzgl. '
        'Abschlaege",\n'
        '  "items": [{"description": "Gesamtleistung Projekt PROJ-2025-42", '
        '"quantity": "1", "unit_price": "50000.00", "tax_rate": "19.00"}]\n'
        "}\n"
        "```\n\n"
        "## Steuerliche Behandlung\n"
        "- USt wird **pro Abschlagsrechnung** geschuldet (§13 Abs. 1 Nr. 1a UStG)\n"
        "- Vorsteuerabzug beim Empfaenger mit jeder Abschlagsrechnung moeglich\n"
        "- Schlussrechnung verrechnet bereits gezahlte USt ueber `prepaid_amount`\n"
        "- **DuePayableAmount = GrossTotal - PrepaidAmount**\n\n"
        "## Wichtige Regeln\n"
        "- Gleiche Projektreferenz (BT-11) in allen Dokumenten\n"
        "- `prepaid_amount` (BT-113) in Schlussrechnung = Summe aller Abschlaege (netto + USt)\n"
        "- TypeCode 875 (Teilrechnung), 876 (Vorauszahlungsrechnung), "
        "877 (Schlussrechnung)\n"
        "- Jede Rechnung erhaelt eigene fortlaufende Nummer\n\n"
        "## Haeufige Fehler\n"
        "- Unterschiedliche Projektreferenzen in Teil- vs. Schlussrechnung\n"
        "- PrepaidAmount vergessen → Doppelberechnung\n"
        "- TypeCode 380 statt 875/877 verwendet\n"
        "- USt auf Abschlagsrechnungen nicht als Vorsteuer beruecksichtigt"
    )


def innergemeinschaftliche_deep_dive() -> str:
    """Innergemeinschaftliche Lieferung: Vollstaendige Compliance."""
    return (
        "# Innergemeinschaftliche Lieferung — Deep Dive\n\n"
        "## Rechtsgrundlage\n"
        "- §4 Nr. 1b UStG i.V.m. §6a UStG\n"
        "- Art. 138 MwStSystRL\n"
        "- Steuerbefreiung nur bei **vollstaendigem Nachweisset**\n\n"
        "## Voraussetzungen (alle muessen erfuellt sein)\n"
        "1. Lieferung eines Gegenstands\n"
        "2. Gegenstand gelangt in anderen EU-Mitgliedstaat\n"
        "3. Erwerber ist Unternehmer mit gueltiger USt-IdNr.\n"
        "4. Erwerber besteuert den innergemeinschaftlichen Erwerb\n\n"
        "## E-Rechnungs-Felder\n"
        "- `tax_category`: 'K' (Intra-Community)\n"
        "- `tax_rate`: '0.00'\n"
        "- `tax_exemption_reason_code`: 'VATEX-EU-IC'\n"
        "- `tax_exemption_reason`: 'Steuerfreie innergemeinschaftliche "
        "Lieferung gemaess §4 Nr. 1b i.V.m. §6a UStG'\n"
        "- `seller_vat_id`: DE-USt-IdNr. (BT-31, Pflicht!)\n"
        "- `buyer_vat_id`: USt-IdNr. des Erwerbers (BT-48, Pflicht!)\n\n"
        "## Nachweispflichten\n\n"
        "### 1. Gelangensbestaetigung (§17a UStDV)\n"
        "Bevorzugter Nachweis — bestaetigt:\n"
        "- Name/Anschrift des Abnehmers\n"
        "- Menge/Bezeichnung der Ware\n"
        "- Ort + Monat des Erhalts im anderen Mitgliedstaat\n"
        "- Ausstellungsdatum + Unterschrift\n\n"
        "### 2. Alternative Nachweise (§17b UStDV)\n"
        "| Transportart | Nachweis |\n"
        "|-------------|----------|\n"
        "| Strasse | CMR-Frachtbrief + Empfangsbestaetigung |\n"
        "| Schiene | CIM-Frachtbrief |\n"
        "| Luft | IATA-Luftfrachtbrief |\n"
        "| See | Konnossement (Bill of Lading) |\n"
        "| Post | Einlieferungsbeleg + Zahlungsnachweis |\n"
        "| Abholfall | Verbringungsnachweis (§17b Abs. 3 UStDV) |\n\n"
        "## Zusammenfassende Meldung (ZM)\n"
        "- **Pflicht** bei jeder innergemeinschaftlichen Lieferung\n"
        "- Frist: 25. des Folgemonats (bei monatlicher Meldung)\n"
        "- Inhalt: USt-IdNr. des Erwerbers + Bemessungsgrundlage\n"
        "- Elektronische Uebermittlung via ELSTER/BZSt\n"
        "- Bei verspaeteter Meldung: Bussgeld bis 5.000 EUR\n\n"
        "## USt-IdNr.-Pruefung\n"
        "- **Qualifizierte Bestaetigung** ueber BZSt (eVatR)\n"
        "- Einfache Pruefung: MIAS/VIES der EU-Kommission\n"
        "- Pruefung **vor** Lieferung dokumentieren!\n"
        "- Bei ungueltiger USt-IdNr.: Keine Steuerbefreiung!\n\n"
        "## Haeufige Fehler\n"
        "- Fehlende USt-IdNr. des Kaeufers auf der Rechnung\n"
        "- ZM nicht oder zu spaet eingereicht\n"
        "- Gelangensbestaetigung fehlt → Steuerbefreiung verloren\n"
        "- USt-IdNr. nicht vorab geprueft (keine Dokumentation)\n"
        "- Tax Category 'S' statt 'K' in der E-Rechnung"
    )


def skonto_berechnung_guide() -> str:
    """Skonto: Korrekte Berechnung und steuerliche Behandlung."""
    return (
        "# Skonto — Berechnung und Steuerliche Behandlung\n\n"
        "## Was ist Skonto?\n"
        "Ein Preisnachlass fuer fruehzeitige Zahlung. In Deutschland "
        "ueblich: 2-3% bei Zahlung innerhalb von 10-14 Tagen.\n\n"
        "## E-Rechnungs-Felder\n"
        "- `skonto_percent`: z.B. '2.00'\n"
        "- `skonto_days`: z.B. '10'\n"
        "- `payment_terms_text` (BT-20): Freitext, z.B.:\n"
        "  'Zahlbar innerhalb 30 Tagen netto. "
        "2% Skonto bei Zahlung innerhalb 10 Tagen.'\n\n"
        "## XRechnung-Kodierung in BT-20\n"
        "Fuer maschinelle Verarbeitung wird Skonto in BT-20 "
        "nach XRechnung-Konvention kodiert:\n"
        "```\n"
        "#SKONTO#TAGE=10#PROZENT=2.00#\n"
        "```\n"
        "Mehrere Skontostaffeln:\n"
        "```\n"
        "#SKONTO#TAGE=10#PROZENT=3.00#\n"
        "#SKONTO#TAGE=20#PROZENT=2.00#\n"
        "#SKONTO#TAGE=30#PROZENT=0.00#\n"
        "```\n\n"
        "## Steuerliche Behandlung (§17 Abs. 1 UStG)\n\n"
        "### Beim Rechnungssteller (Leistender)\n"
        "- Skonto **reduziert die Bemessungsgrundlage** (Entgelt)\n"
        "- USt-Schuld verringert sich entsprechend\n"
        "- Berichtigung im Voranmeldungszeitraum der Skontogewaehrung\n\n"
        "### Beim Rechnungsempfaenger\n"
        "- Vorsteuerabzug nur auf den **tatsaechlich gezahlten** Betrag\n"
        "- Bei Skontoabzug: Vorsteuerberichtigung erforderlich\n"
        "- In der Praxis: Buchung beim Zahlungseingang\n\n"
        "## Berechnungsbeispiel\n"
        "```\n"
        "Rechnungsbetrag netto:     1.000,00 EUR\n"
        "USt 19%:                     190,00 EUR\n"
        "Brutto:                    1.190,00 EUR\n"
        "\n"
        "Bei 2% Skonto:\n"
        "Skontobasis (brutto):      1.190,00 EUR\n"
        "Skonto 2%:                    23,80 EUR\n"
        "Zahlbetrag:                1.166,20 EUR\n"
        "\n"
        "Korrigierte Werte:\n"
        "Netto nach Skonto:           980,00 EUR\n"
        "USt nach Skonto:             186,20 EUR\n"
        "```\n\n"
        "## Brutto- vs. Netto-Skonto\n"
        "| Methode | Formel | Praxis |\n"
        "|---------|--------|--------|\n"
        "| Brutto-Skonto | Skonto auf Bruttobetrag | **Standard in DE** |\n"
        "| Netto-Skonto | Skonto nur auf Nettobetrag | Seltener |\n\n"
        "In der E-Rechnung ist Brutto-Skonto der Standard "
        "(§17 Abs. 1 Satz 1 UStG).\n\n"
        "## Skonto + Ratenzahlung\n"
        "- Skonto gilt nur auf erste Rate? → Vertraglich regeln\n"
        "- Standard: Skonto auf Gesamtbetrag, nicht pro Rate\n"
        "- In BT-20 alle Bedingungen klar dokumentieren\n\n"
        "## Haeufige Fehler\n"
        "- Skonto nur auf Nettobetrag berechnet (falsch in DE!)\n"
        "- Vorsteuerberichtigung beim Empfaenger vergessen\n"
        "- Skonto-Kodierung in BT-20 fehlt oder falsch formatiert\n"
        "- USt-Berichtigung beim Rechnungssteller vergessen\n"
        "- Skontofrist beginnt ab Rechnungsdatum, nicht Lieferdatum"
    )
